<?php
/**
 * @author    Ilya Kushnir ilya.kush@gmail.com
 * @var \Magento\Backend\Block\Template            $block
 * @var \Magento\Framework\Escaper                 $escaper
 */
?>
<?php if ($block->getPaymentLink()): ?>
    <table class="data-table admin__table-secondary">
        <tbody>
            <tr>
                <th><?= $escaper->escapeHtml(__('Payment Link')) ?></th>
                <td>
                    <a target="_blank"
                       href="<?= $escaper->escapeUrl($block->getPaymentLink()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('Go to payment page')) ?>">
                        <?= $escaper->escapeHtml(__('Go to payment page')) ?>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>
