<?php
/**
 * @author    Ilya Kushnir ilya.kush@gmail.com
 * @var \Magento\Framework\View\Element\Template   $block
 * @var \Magento\Framework\Escaper                 $escaper
 */
?>
<?php if ($block->getPaymentLink()): ?>
    <p>
        <a target="_blank"
           href="<?= $escaper->escapeUrl($block->getPaymentLink()) ?>"
           title="<?= $escaper->escapeHtmlAttr(__('Go to payment page')) ?>">
            <?= $escaper->escapeHtml(__('Go to payment page')) ?>
        </a>
    </p>
<?php endif; ?>
